function OK = ConvertDATtoCluster(filepath)
% Converts a spike .dat file generated by ntrode into a .cluster file
% Randy Bruno, Feb 2011

if (nargin==0)
   [filename pathname OK] = uigetfile('*.dat', 'Select a .dat file to convert');
   filepath = [pathname filename];
end

clust = ReadDAT(filepath);
OK = WriteCluster([filepath(1:(end-3)) 'cluster0'], clust);
if ~OK
    uiwait(errordlg('could not write cluster file', '', 'modal'));
end
