function nSpikes = GetNumberOfSpikes(filepath)
% GETNUMBEROFSPIKES Calculates the number of spikes in a .dat file
% generated by ntrode.vi.
% GETNUMBEROFSPIKES(FILEPATH), where FILEPATH is a file identifier,
% returned the number of spikes in the .dat file.
% Randy Bruno, May 2003

RECSIZE = 140; % record size in bytes

fid = fopen(filepath, 'r', 'b');
if (fid == -1)
    error('GetNumberOfSpikes.m could not open file for reading.');
end
headerSize = SkipHeader(fid);

fseek(fid, 0, 'eof');
nSpikes = (ftell(fid) - headerSize) / RECSIZE ;

if (nSpikes ~= floor(nSpikes))
    errordlg('error computing number of spikes -- may not be a spike file');
    error('error computing number of spikes -- may not be a spike file');
end

fclose(fid);
