function stimuli = GetStimCodes(filepath, duration, checkCodes)
% Identifies the unique stimulus codes in a continuous signal .dat file
% generated by ntrode.vi.
%
% Randy Bruno, June 2003

if (nargin == 0)
    [filename pathname OK] = uigetfile('*.dat', 'Select continuous signal file');
    if (~OK) return; end
    filepath = [pathname, filename];
    duration = input('Trial duration in msec: ');
end

if nargin < 3
    checkCodes = true;
end

SAMPLERATE = 32000; % in Hz
recSize = (SAMPLERATE * (duration / 1000) + 1) * 4; %in bytes

fid = fopen(filepath, 'r', 'b');
if (fid == -1) error('could not open file for reading'); end
headerSize = SkipHeader(fid);

i = 0;
stimuli = [];
while (~feof(fid))
    status = fseek(fid, i*recSize + headerSize, 'bof');
    if (status == -1)
        warning(['could not seek to start of record #' num2str(i)]);
        break;
    end
    stimulus = fread(fid, 1, 'float32');
    %if (checkCodes & stimulus >= 0) error('invalid stimulus code; check duration parameter'); end
    stimuli = [stimuli, stimulus];
    i = i + 1;
end
stimuli = unique(stimuli);
fclose(fid);
