function cluster = ReadDAT(filepath)
% READDAT Read a .dat file, generated by ntrode.vi, that contains SPIKES
% READDAT(FILENAME), where FILENAME is a string specifying a file,
% returns an array of timestamps and trial information.
% Randy Bruno, May 2003

if (nargin==0)
   [filename pathname OK] = uigetfile('*.dat', 'Select a .dat file to read');
   filepath = [pathname filename];
end

nSpikes = GetNumberOfSpikes(filepath);

fid = fopen(filepath, 'r', 'b');
if (fid == -1)
    error('ReadDAT.m could not open file for reading.');
end
headerSize = SkipHeader(fid);

for i = 1:nSpikes
    [timestamp(i), trial(i), stimcode(i)] = GetOneSpike(fid);
end

timestamp = timestamp / 10;
cluster = [(0:(nSpikes-1))', trial', stimcode', timestamp'];

fclose(fid);
disp(['Read ', num2str(nSpikes), ' records']);
