function [headerSize, header] = SkipHeader(fid, str)
% SKIPHEADER Skips the header of a .dat file generated by ntrode.vi
% SKIPHEADER(FID), where FID is a file identifier,
% advances the file pointer to the just after the header
% and returns the header length in bytes.

if nargin < 2
    str = '%%ENDHEADER';
end

header = {};
done = false;
while ~done
    line = fgetl(fid);
    if feof(fid)
        error('SkipHeader.m encountered the end of the file.')
    end
    header{length(header) + 1} = line;
    done = strcmp(line, str);
end
headerSize = ftell(fid);
