function GeneralizedCutter(currentClusters, featureData, featureNames, clusterType)

% GeneralizedCutter(currentClusters, featureData, featureNames)
% 
% INPUTS
%     currentClusters 
%     featureData = nS x nD data
%     featureNames = names of feature data dimensions
%
% OUTPUTS
%     modifies MClust_Clusters
%
% ADR 1998
% version M1.0
% RELEASED as part of MClust 2.0
% See standard disclaimer in Contents.m

global MClust_Autosave
MClust_Autosave = 10;

%--------------------------------
% constants to make everything identical

uicHeight = 0.05;
uicWidth  = 0.175;
uicWidth0 = 0.075;
uicWidth1 = 0.10;
dX = 0.3;
XLocs = [0.05 0.40:uicWidth1:0.9];
dY = 0.05;
YLocs = 0.9:-dY:0.05;
FrameBorder = 0.01;

% -------------------------------
% if given clusters, generate convex hull representations
global MClust_Clusters MClust_FeatureData
MClust_Clusters = {};
nClusters = length(currentClusters);
if ~isempty(currentClusters)
   for iC = 1:nClusters
      DisplayProgress(iC, nClusters, 'Title', 'Converting clusters');
      if isa(currentClusters{iC}, clusterType)         
         MClust_Clusters{iC} = currentClusters{iC};
      else
         f = FindInCluster(currentClusters{iC}, MClust_FeatureData);
         MClust_Clusters{iC} = feval(clusterType, featureData(f,:));
      end
   end
end

%-------------------------------
% figure

figHandle = figure(...
   'Name', ['Cluster Cutting Control Window (', clusterType, ')'],...
   'NumberTitle', 'off', ...
   'Tag', 'ClusterCutWindow', ...
   'HandleVisibility', 'Callback', ...
   'UserData', featureData, ...
   'Position', [10 60 400 650], ...
   'CreateFcn', 'GeneralizedCutterCallbacks');

% -------------------------------
% axes
uicontrol('Parent', figHandle, ...
   'Units', 'Normalized', 'Position', [XLocs(1) YLocs(1) uicWidth0 + uicWidth uicHeight], ...
   'Style', 'text', 'String', 'Axes');
uicontrol('Parent', figHandle, ...
   'Units', 'Normalized', 'Position', [XLocs(1) YLocs(2) uicWidth0 uicHeight], ...
   'Style', 'text', 'String', ' X: ');
uicontrol('Parent', figHandle, ...
   'Units', 'Normalized', 'Position', [XLocs(1)+uicWidth0 YLocs(2) uicWidth uicHeight],...
   'Style', 'popupmenu', 'Tag', 'xdim', 'String', featureNames, ...
   'Callback', 'GeneralizedCutterCallbacks', 'Value', 1, ...
   'TooltipString', 'Select x dimension');
uicontrol('Parent', figHandle, ...
   'Units', 'Normalized', 'Position', [XLocs(1) YLocs(3) uicWidth0 uicHeight], ...
   'Style', 'text', 'String', ' Y: ');
uicontrol('Parent', figHandle, ...
   'Units', 'Normalized', 'Position', [XLocs(1)+uicWidth0 YLocs(3) uicWidth uicHeight],...
   'Style', 'popupmenu', 'Tag', 'ydim', 'String', featureNames, ...
   'Callback', 'GeneralizedCutterCallbacks', 'Value', 2, ...
   'TooltipString', 'Select y dimension');

uicontrol('Parent', figHandle, ...
   'Units', 'Normalized', 'Position', [XLocs(1) YLocs(4) uicWidth0 uicHeight], ...
   'Style', 'pushbutton', 'Tag', 'PrevAxis', 'String', '<', 'Callback', 'GeneralizedCutterCallbacks', ...
   'TooltipString', 'Step backwards');
uicontrol('Parent', figHandle, ...
   'Units', 'Normalized', 'Position', [XLocs(1)+uicWidth0 YLocs(4) uicWidth-uicWidth0 uicHeight], ...
   'Style', 'text', 'String', 'Axis');
uicontrol('Parent', figHandle, ...
   'Units', 'Normalized', 'Position', [XLocs(1)+uicWidth YLocs(4) uicWidth0 uicHeight], ...
   'Style', 'pushbutton', 'Tag', 'NextAxis', 'String', '>', 'Callback', 'GeneralizedCutterCallbacks', ...
   'TooltipString', 'Step forwards');
uicontrol('Parent', figHandle, ...
   'Units', 'Normalized', 'Position', [XLocs(1) YLocs(5) uicWidth+uicWidth0 uicHeight], ...
   'Style', 'checkbox', 'Tag', 'ViewAllDimensions', 'String', 'View all dimensions', ...
   'Value', 0, 'Callback', 'GeneralizedCutterCallbacks', ...
   'TooltipString','Continuously step through all dimension pairs');
uicontrol('Parent', figHandle, ...
   'Units', 'Normalized', 'Position', [XLocs(1) YLocs(6) uicWidth+uicWidth0 uicHeight], ...
   'Style', 'checkbox','Value', 0, 'Tag', 'RedrawAxes', 'String', 'Redraw Axes', ...
   'Callback', 'GeneralizedCutterCallbacks', ...
   'TooltipString', 'If checked, redraw axes with each update.  Uncheck and recheck to redraw axes now.');
uicontrol('Parent', figHandle, ...
   'Units', 'Normalized', 'Position', [XLocs(1) YLocs(7) uicWidth-uicWidth0 uicHeight], ...
   'Style', 'text', 'String', 'Marker');
uicontrol('Parent', figHandle, ...
   'Units', 'Normalized', 'Position', [uicWidth+XLocs(1)-uicWidth0 YLocs(7) uicWidth0 uicHeight], ...
   'Style', 'popupmenu', 'Value', 1, 'Tag', 'PlotMarker', ...
   'String', {'.','o','x','+','*','s','d','v','^','<','>','p','h'}, ...
   'Callback', 'GeneralizedCutterCallbacks', ...
   'TooltipString', 'Change marker');
uicontrol('Parent', figHandle, ...
   'Units', 'Normalized', 'Position', [uicWidth+XLocs(1) YLocs(7) uicWidth0 uicHeight], ...
   'Style', 'popupmenu', 'Value', 1, 'Tag', 'PlotMarkerSize', ...
   'String', {1,2,3,4,5,10,15,20,25}, ...
   'Callback', 'GeneralizedCutterCallbacks', ...
   'TooltipString', 'Change marker size');
uicontrol('Parent', figHandle, ...
   'Units', 'Normalized', 'Position', [XLocs(1) YLocs(8) uicWidth+uicWidth0 uicHeight], ...
   'Style', 'pushbutton', 'String', 'ShowContourPlot', 'Tag', 'ContourPlot', ...
   'Callback', 'GeneralizedCutterCallbacks', ...
   'TooltipString', 'Contour plot of current axis');

%----------------------------------
% general control
uicontrol('Parent', figHandle, ...
   'Units', 'Normalized', 'Position', [XLocs(1) YLocs(10) uicWidth+uicWidth0 uicHeight], ...
   'UserData', clusterType, ...
   'Style', 'pushbutton', 'String', 'Add Cluster', 'Tag', 'Add Cluster', ...
   'Callback', 'GeneralizedCutterCallbacks', ...
   'TooltipString', 'Add a cluster object');
uicontrol('Parent', figHandle, ...
   'Units', 'Normalized', 'Position', [XLocs(1) YLocs(11) (uicWidth+uicWidth0)/2 uicHeight], ...
   'Style', 'pushbutton', 'String', 'Hide', 'Tag', 'HideAll', ...
   'Callback', 'GeneralizedCutterCallbacks', ...
   'TooltipString', 'Hide all clusters');
uicontrol('Parent', figHandle, ...
   'Units', 'Normalized', 'Position', [XLocs(1)+(uicWidth+uicWidth0)/2 YLocs(11) (uicWidth+uicWidth0)/2 uicHeight], ...
   'Style', 'pushbutton', 'String', 'Show', 'Tag', 'ShowAll', ...
   'Callback', 'GeneralizedCutterCallbacks', ...
   'TooltipString', 'Show all clusters');
uicontrol('Parent', figHandle, ...
   'Units', 'Normalized', 'Position', [XLocs(1) YLocs(12) uicWidth+uicWidth0 uicHeight], ...
   'Style', 'pushbutton', 'String', 'Pack Clusters', 'Tag', 'Pack Clusters', ...
   'Callback', 'GeneralizedCutterCallbacks', ...
   'TooltipString', 'Pack clusters; clear unused clusters');

uicontrol('Parent', figHandle, ...
   'Units', 'Normalized', 'Position', [XLocs(1) YLocs(13) uicWidth+uicWidth0 uicHeight], ...
   'Style', 'pushbutton', 'String', 'Undo', 'Tag', 'Undo', ...
   'Callback', 'GeneralizedCutterCallbacks', ...
   'TooltipString', 'Undo one step');

uicontrol('Parent', figHandle, ...
   'Units', 'Normalized', 'Position', [XLocs(1) YLocs(15) uicWidth+uicWidth0 uicHeight], ...
   'Style', 'pushbutton','Tag', 'CheckClusters', 'String', 'Check clusters', 'Callback', 'GeneralizedCutterCallbacks', ...
   'TooltipString', 'Check all clusters');

uicontrol('Parent', figHandle, ...
   'Units', 'Normalized', 'Position', [XLocs(1) YLocs(16) uicWidth+uicWidth0 uicHeight], ...
   'Style', 'pushbutton','Tag', 'EvalOverlap', 'String', 'Eval overlap', 'Callback', 'GeneralizedCutterCallbacks', ...
   'TooltipString', 'Eval overlap between all cluster pairs');

uicontrol('Parent', figHandle, ...
   'Units', 'Normalized', 'Position', [XLocs(1) YLocs(17) uicWidth+uicWidth0 uicHeight], ... 
   'Style', 'pushbutton', 'Tag', 'Autosave', 'String', ['Autosave in ' num2str(MClust_Autosave)], ...
   'Callback', 'GeneralizedCutterCallbacks', ... 
   'TooltipString', 'Count steps to autosave'); 

uicontrol('Parent', figHandle, ...
   'Units', 'Normalized', 'Position', [XLocs(1) YLocs(end) uicWidth+uicWidth0 uicHeight], ...
   'Style', 'pushbutton', 'Tag', 'Exit', 'String', 'Exit', ...
   'Callback', 'GeneralizedCutterCallbacks', ...
   'TooltipString', 'Return to main window');

uicontrol('Parent', figHandle, ...
    'Units', 'Normalized', 'Position', [XLocs(end) YLocs(end) uicWidth0/2 length(YLocs) * dY], ...
    'Style', 'slider', 'Tag', 'ScrollClusters', 'Callback', 'GeneralizedCutterCallbacks', ...
    'Value', 0', 'Min', -99, 'Max', 0, ...
    'TooltipString', 'Scroll clusters');
