function MClust

% MClust main window
% 
% Each uicontrol is given a Tag that is descriptive of its
% role.  All callbacks are sent to MClustCallbacks.  There
% a switch statement will case on the Tag to run each routine.
%
% ADR 1998
% version M2.0 
% RELEASED as part of MClust 2.0
% See standard disclaimer in Contents.m

%----------------------------------
% set up global variables
global MClust_TTData MClust_FeatureData
global MClust_Clusters;
MClust_Clusters = {};

global MClust_Colors
MClust_Colors = colorcube; close;
featuresToUse = [];

global MClust_Hide MClust_UnaccountedForOnly
MClust_Hide = zeros(64,1);
MClust_UnaccountedForOnly = 0;

MClust_FileType = [];

global MClustDirectory
MClustDirectory = fileparts(which('MClust'));

% read defaults if available
fp = fopen('defaults.mclust');
if fp == -1
   pushdir(MClustDirectory);
   fp = fopen('defaults.mclust');
else 
   pushdir;
end
if fp ~= -1
   fclose(fp);
   load defaults.mclust -mat
end
popdir;

%----------------------------------
% main window

MClustMainFigureHandle = figure(...
   'Name','MClust', ...
   'NumberTitle','off', ...   
   'Tag','MClustMainWindow', ...,
   'Resize', 'Off', ...
   'Units', 'Normalized', ...
   'HandleVisibility', 'Callback');

%-------------------------------
% Alignment variables

uicHeight = 0.05;
uicWidth  = 0.25;
dX = 0.3;
XLocs = 0.1:dX:0.9;
dY = 0.05;
YLocs = 0.9:-dY:0.1;
FrameBorder = 0.01;


% Buttons and status

uicontrol('Parent', MClustMainFigureHandle, ... 
   'Units', 'Normalized', 'Position', [XLocs(1)-FrameBorder YLocs(end)-FrameBorder dX 0.85+2*FrameBorder], ...
   'Style', 'frame');

global MClust_TTfn
if ~isempty(MClust_TTfn)
   [curdn, curfn] = fileparts(MClust_TTfn);
else
   curfn = [];
end
uicontrol('Parent', MClustMainFigureHandle, ...
   'Units', 'Normalized', 'Position', [XLocs(1) YLocs(1) uicWidth uicHeight], ...
   'Style', 'Text', 'String', curfn, 'Tag', 'TTFileName')

uicontrol('Parent', MClustMainFigureHandle, ...  
   'Units', 'Normalized', 'Position', [XLocs(1) YLocs(2) uicWidth/2 uicHeight], ...
   'Style', 'CheckBox', 'String', 'Load file',  'Tag', 'LoadTTFileButton', ...
   'Value', ~isempty(MClust_TTData), 'Callback', 'MClustCallbacks', ...
   'TooltipString', 'Load input file'); 

if isempty(MClust_FileType), MClust_FileType = 1; end
uicontrol('Parent', MClustMainFigureHandle, ...  
   'Units', 'Normalized', 'Position', [XLocs(1)+uicWidth/2 YLocs(2) uicWidth/2 uicHeight], ...
   'Style', 'popupmenu', 'Tag', 'InputType', 'String', {'TT sun', 'TT nt', 'ST nt', 'SE nt'}, ...
   'Value', MClust_FileType, 'Callback', 'MClustCallbacks', ...
   'TooltipString', 'Select input file type: TT=Tetrode; ST=Stereotrode; SE=SingleElectrode'); 

ui_ChooseFeaturesButton = ...
   uicontrol('Parent', MClustMainFigureHandle, ...
   'Units', 'Normalized', 'Position', [XLocs(1) YLocs(3) uicWidth uicHeight], ...
   'Style', 'CheckBox', 'String', 'Choose features', 'Tag', 'ChooseFeaturesButton', 'Enable', 'inactive',...
   'TooltipString', 'Choose features using listboxes to your right');

uicontrol('Parent', MClustMainFigureHandle, ...
   'Units', 'Normalized', 'Position', [XLocs(1) YLocs(4) uicWidth uicHeight], ...
   'Style', 'CheckBox',  'String', 'Calculate features', 'Tag', 'CalculateFeaturesButton', ...
   'Value', ~isempty(MClust_FeatureData), 'Callback', 'MClustCallbacks', ...
   'TooltipString', 'Calculate features for processing');


uicontrol('Parent', MClustMainFigureHandle, ...
   'Units', 'Normalized', 'Position', [XLocs(1) YLocs(7) uicWidth uicHeight], ...
   'Style', 'PushButton', 'String', 'Cut: Convex Hulls', 'Tag', 'CutWithConvexHulls', ...
   'Callback', 'MClustCallbacks', ...
   'TooltipString', 'Cut clusters using convex hulls in pairs of dimensions');


uicontrol('Parent', MClustMainFigureHandle, ...
   'Units', 'Normalized', 'Position', [XLocs(1) YLocs(10) uicWidth uicHeight], ...
   'Style', 'PushButton', 'String', 'ViewClusters', 'Tag', 'ViewClusters', ...
   'Callback', 'MClustCallbacks', ...
   'TooltipString', 'View already cut clusters');

uicontrol('Parent', MClustMainFigureHandle, ...
   'Units', 'Normalized', 'Position', [XLocs(1) YLocs(14) uicWidth uicHeight], ...
   'Style', 'PushButton', 'String', 'Write Files', 'Tag', 'WriteFiles', 'Callback', 'MClustCallbacks', ...
   'TooltipString', 'Write clusters to disk.  Writes t-files, cluster-files, and cut-files.');

uicontrol('Parent', MClustMainFigureHandle, ...
   'Units', 'Normalized', 'Position', [XLocs(1) YLocs(17) uicWidth uicHeight], ...
   'Style', 'PushButton', 'String', 'Exit', 'Tag', 'ExitButton', 'Callback', 'MClustCallbacks', ...
   'TooltipString', 'Exit MClust.');

% Features to use

% Create Feature Listboxes
uicontrol('Parent', MClustMainFigureHandle,...
   'Style', 'text', 'String', 'FEATURES', 'Units', 'Normalized', 'Position', [XLocs(2) YLocs(1) 2*uicWidth uicHeight]);
uicontrol('Parent', MClustMainFigureHandle,...
   'Style', 'text', 'String', 'ignore', 'Units', 'Normalized', 'Position', [XLocs(2) YLocs(2) uicWidth uicHeight]);
ui_featuresIgnoreLB =  uicontrol('Parent', MClustMainFigureHandle,...
   'Units', 'Normalized', 'Position', [XLocs(2) YLocs(8) uicWidth 6*uicHeight],...
   'Style', 'listbox', 'Tag', 'FeaturesIgnoreListbox',...
   'Callback', 'MClustCallbacks',...
   'HorizontalAlignment', 'right', ...
   'TooltipString', 'These are features which will not be included but are available.  Click to use.');
uicontrol('Parent', MClustMainFigureHandle,...
   'Style', 'text', 'String', 'use', 'Units', 'Normalized', 'Position', [XLocs(2)+uicWidth YLocs(2) uicWidth uicHeight]);
ui_featuresUseLB = uicontrol('Parent', MClustMainFigureHandle,...
   'Units', 'Normalized', 'Position', [XLocs(2)+uicWidth YLocs(8) uicWidth 6*uicHeight],...
   'Style', 'listbox', 'Tag', 'FeaturesUseListbox',...
   'Callback', 'MClustCallbacks',...
   'HorizontalAlignment', 'right', ...
   'TooltipString', 'These features will be used.  Click to ignore.');
set(ui_featuresIgnoreLB, 'UserData', ui_featuresUseLB);
set(ui_featuresUseLB,    'UserData', ui_featuresIgnoreLB);

featureFiles =  sortcell(FindFiles('feature_*.m', 'StartingDirectory', MClustDirectory,'CheckSubdirs', 0));
featureIgnoreString = {};
featureUseString = {};
for iF = 1:length(featureFiles)
   [dummy, featureFiles{iF}] = fileparts(featureFiles{iF});
   featureFiles{iF} = featureFiles{iF}(9:end); % cut "feature_" off front for display
   if any(strcmp(featureFiles{iF}, featuresToUse))
      featureUseString = cat(1, featureUseString, featureFiles(iF));
   else
      featureIgnoreString = cat(1, featureIgnoreString, featureFiles(iF));
   end
end
set(ui_featuresIgnoreLB, 'String', featureIgnoreString);
set(ui_featuresUseLB, 'String', featureUseString);
if ~isempty(ui_featuresUseLB)
   set(ui_ChooseFeaturesButton, 'Value', 1);
end

% tetrode validity
uicontrol('Parent', MClustMainFigureHandle,...
   'Units', 'Normalized', 'Position', [XLocs(2) YLocs(9) 2*uicWidth uicHeight],...
   'Style', 'text', 'String', 'CHANNEL VALIDITY');
uicontrol('Parent', MClustMainFigureHandle,...
   'Units', 'Normalized', 'Position', [XLocs(2)+0*uicWidth/2 YLocs(10) uicWidth/2 uicHeight],...   
   'Style', 'checkbox', 'String', 'Ch 1', 'Tag', 'TTValidity1', 'Value', 1, 'HorizontalAlignment', 'left', ...
   'TooltipString', 'Include channel 1 in feature calculation.');
uicontrol('Parent', MClustMainFigureHandle,...
   'Units', 'Normalized', 'Position', [XLocs(2)+1*uicWidth/2 YLocs(10) uicWidth/2 uicHeight],...   
   'Style', 'checkbox', 'String', 'Ch 2', 'Tag', 'TTValidity2', 'Value', 0, 'HorizontalAlignment', 'left', ...
   'TooltipString', 'Include channel 2 in feature calculation.');
uicontrol('Parent', MClustMainFigureHandle,...
   'Units', 'Normalized', 'Position', [XLocs(2)+2*uicWidth/2 YLocs(10) uicWidth/2 uicHeight],...   
   'Style', 'checkbox', 'String', 'Ch 3', 'Tag', 'TTValidity3', 'Value', 0, 'HorizontalAlignment', 'left', ...
   'TooltipString', 'Include channel 3 in feature calculation.');
uicontrol('Parent', MClustMainFigureHandle,...
   'Units', 'Normalized', 'Position', [XLocs(2)+3*uicWidth/2 YLocs(10) uicWidth/2 uicHeight],...   
   'Style', 'checkbox', 'String', 'Ch 4', 'Tag', 'TTValidity4', 'Value', 0, 'HorizontalAlignment', 'left', ...
   'TooltipString', 'Include channel 4 in feature calculation.');


% Loading and saving components
uicontrol('Parent', MClustMainFigureHandle, ...
   'Units', 'Normalized', 'Position', [XLocs(2)-FrameBorder YLocs(end)-FrameBorder 2*(uicWidth+FrameBorder) uicHeight*7], ...
   'Style', 'frame');

uicontrol('Parent', MClustMainFigureHandle, ...
   'Units', 'Normalized', 'Position', [XLocs(2) YLocs(12) uicWidth uicHeight], ...
   'Style', 'PushButton', 'String', 'Load clusters', 'Tag', 'LoadClusters', 'Callback', 'MClustCallbacks', ...
   'TooltipString', 'Load already cut clusters. Features and channel validity MUST BE identical to previous session.');
uicontrol('Parent', MClustMainFigureHandle, ...
   'Units', 'Normalized', 'Position', [XLocs(2) YLocs(13) uicWidth uicHeight], ...
   'Style', 'PushButton', 'String', 'Save clusters', 'Tag', 'SaveClusters', 'Callback', 'MClustCallbacks', ...
   'TooltipString', 'Save clusters but do not write t-files.');
uicontrol('Parent', MClustMainFigureHandle, ...
   'Units', 'Normalized', 'Position', [XLocs(2) YLocs(14) uicWidth uicHeight], ...
   'Style', 'PushButton', 'String', 'Clear Clusters', 'Tag', 'ClearClusters', ...
   'Callback', 'MClustCallbacks', ...
   'TooltipString', 'Clear clusters.  No undo available.');
uicontrol('Parent', MClustMainFigureHandle, ...
   'Units', 'Normalized', 'Position', [XLocs(2) YLocs(17) uicWidth uicHeight], ...
   'Style', 'PushButton', 'String', 'Load defaults', 'Tag', 'LoadDefaults', 'Callback', 'MClustCallbacks', ...
   'TooltipString', 'Load defaults.  Defaults include color scheme, features, and channel validity.');
uicontrol('Parent', MClustMainFigureHandle, ...
   'Units', 'Normalized', 'Position', [XLocs(2) YLocs(16) uicWidth uicHeight], ...
   'Style', 'PushButton', 'String', 'Save defaults', 'Tag', 'SaveDefaults', 'Callback', 'MClustCallbacks', ...
   'TooltipString', 'Save defaults.  Defaults include color scheme, features, and channel validity.');

uicontrol('Parent', MClustMainFigureHandle, ...
   'Units', 'Normalized', 'Position', [XLocs(2)+uicWidth YLocs(end) uicWidth uicHeight * 6], ...
   'Style', 'text', 'String', { 'MClust', '1998-2000', '', 'By A. David Redish'});